# .github/workflows/ci.yml
name: CI – Tauri Desktop Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04          # single platform for speed :contentReference[oaicite:0]{index=0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js & cache
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
          cache: 'npm'          # speeds up npm installs :contentReference[oaicite:1]{index=1}

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
                              # only core libs for Linux :contentReference[oaicite:2]{index=2}

      - name: Install frontend dependencies
        working-directory: apps/desktop
        run: npm ci              # requires package-lock.json :contentReference[oaicite:3]{index=3}

      - name: Build Tauri App
        working-directory: apps/desktop
        run: npm run tauri build
