name: Build & Release Tauri App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    # matrix across Linux, macOS x64/arm64, Windows
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-22.04
            platform-deps: |
              sudo apt-get update
              sudo apt-get install -y \
                libwebkit2gtk-4.1-dev \
                libappindicator3-dev \
                librsvg2-dev \
                patchelf
          - platform: macos-latest
            platform-deps: echo
          - platform: macos-latest
            platform-deps: echo
            args: --target aarch64-apple-darwin
          - platform: macos-latest
            platform-deps: echo
            args: --target x86_64-apple-darwin
          - platform: windows-latest
            platform-deps: echo

    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Linux native deps
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          ${{ matrix.platform-deps }}

      - name: Setup Node.js & cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install frontend dependencies
        working-directory: apps/desktop
        run: npm ci

      - name: 🧪 Build & Release via Tauri Action
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: apps/desktop
          args: ${{ matrix.args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
