name: Publish Tauri App

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-22.04
            args: ''
          - platform: macos-latest
            args: '--target x86_64-apple-darwin'
          - platform: macos-latest
            args: '--target aarch64-apple-darwin'
          - platform: windows-latest
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Install Linux dependencies when needed
      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

      # 3. Setup Node + NPM cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 4. Setup Rust and build toolchain
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      # 5. Install frontend deps
      - name: Install frontend dependencies
        working-directory: apps/desktop
        run: npm ci

      # 6. Build & Release with Tauri Action
      - name: 🧪 Build & Publish
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: apps/desktop
          args: ${{ matrix.args }}
          # Optional: tagName, releaseName, releaseDraft, etc.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
